### ISSUE TITLE
Can you release 0.0.1 to pip?

### ISSUE THREAD

**Issue by alexespencer** [GrandMoff100/MealieAPI#15]
I've just spent quite a while debugging why it was using backslashes instead of forward slashes in the API path before I realised my library `raw.py` is different to the repo (you've changed it to `posix.path` not `os.path`. Can we release the current code as 0.0.1?

**Comment by GrandMoff100** [comment]
Sure, no problem.

**Comment by GrandMoff100** [comment]
Done

**Comment by alexespencer** [comment]
Brilliant - thank you.
